"use client";
import { useEffect, useState } from "react";
type Opportunity={keyword:string;intent:string;source:string;demandScore:number;trendScore:number;commercialScore:number;competitionScore:number;vetorFitScore:number;opportunityScore:number;trendDirection:string;impressions:number;clicks:number;ctr:number;position:number|null;suggestedRoute:string;sources:string[]};
type Trend={term:string;traffic:string;trendPercent:number;source:string;sourceUrl:string};
export default function MarketIntelligencePage(){
 const [data,setData]=useState<{opportunities:Opportunity[];trends:Trend[];stored:number;searchConsole:{configured:boolean;period:{startDate:string;endDate:string}}}|null>(null);
 const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [refreshing,setRefreshing]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/admin/market-intelligence",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha");setData(j);}catch(e){setError(e instanceof Error?e.message:"Erro");}finally{setLoading(false);}};
 useEffect(()=>{load()},[]);
 const refresh=async()=>{setRefreshing(true);setError("");try{await load()}finally{setRefreshing(false)}};
 if(loading&&!data)return <div className="py-20 text-center text-[var(--muted)]">Coletando inteligência de mercado...</div>;
 if(error&&!data)return <div className="rounded-xl border border-red-500/30 p-6">{error}</div>;
 return <div>
  <div className="flex flex-wrap items-end justify-between gap-4 mb-8"><div><p className="text-xs uppercase tracking-[0.2em] text-[var(--amber)] font-bold">Fase 12</p><h1 className="font-display text-3xl mt-1">Radar de Mercado & Palavras-chave</h1><p className="text-sm text-[var(--muted)] mt-2">Search Console + Google Autocomplete + Google Trends Trending Now, sem Google Ads.</p></div><button onClick={refresh} disabled={refreshing} className="px-3 py-2 rounded-lg border border-border text-xs">{refreshing?"Atualizando...":"Atualizar radar"}</button></div>
  {error&&<div className="mb-5 rounded-xl border border-red-500/30 p-4 text-sm">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">{[["Palavras priorizadas",data?.opportunities.length||0],["Tendências capturadas",data?.trends.length||0],["GSC configurado",data?.searchConsole.configured?"Sim":"Não"],["Registros salvos",data?.stored||0]].map(([l,v])=><div key={String(l)} className="bg-[var(--surface)] border border-border rounded-xl p-5"><p className="text-xs text-[var(--muted)]">{l}</p><p className="text-2xl font-display text-[var(--amber)] mt-1">{v}</p></div>)}</div>
  <section className="bg-[var(--surface)] border border-border rounded-xl p-5 mb-6"><h2 className="font-heading font-bold text-xl">Top oportunidades</h2><p className="text-xs text-[var(--muted)] mt-1 mb-4">Score relativo do Vetor: demanda observada, tendência, intenção comercial, competição proxy e aderência ao catálogo. Não é volume absoluto.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-[var(--muted)] border-b border-border">{["Keyword","Score","Demanda","Trend","Comercial","Competição","Fit","Impr.","Pos.","Rota"].map(x=><th key={x} className="py-3 pr-3">{x}</th>)}</tr></thead><tbody>{(data?.opportunities||[]).slice(0,50).map((x,i)=><tr key={x.keyword+i} className="border-b border-border/60 align-top"><td className="py-3 pr-3 font-medium">{x.keyword}<div className="text-[10px] text-[var(--muted)] mt-1">{x.intent} · {x.sources.join(", ")}</div></td><td className="py-3 pr-3 font-bold text-[var(--amber)]">{x.opportunityScore}</td><td className="py-3 pr-3">{x.demandScore}</td><td className="py-3 pr-3">{x.trendScore}</td><td className="py-3 pr-3">{x.commercialScore}</td><td className="py-3 pr-3">{x.competitionScore}</td><td className="py-3 pr-3">{x.vetorFitScore}</td><td className="py-3 pr-3">{x.impressions}</td><td className="py-3 pr-3">{x.position??"—"}</td><td className="py-3 max-w-[220px] truncate">{x.suggestedRoute||"avaliar nova rota"}</td></tr>)}</tbody></table></div></section>
  <section className="bg-[var(--surface)] border border-border rounded-xl p-5"><h2 className="font-heading font-bold text-xl">Tendências de busca no Brasil</h2><p className="text-xs text-[var(--muted)] mt-1 mb-4">Google Trends Trending Now, últimas 24h. Tendências gerais são filtradas automaticamente quando cruzam com keywords do Vetor.</p><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{(data?.trends||[]).slice(0,30).map((x,i)=><a key={x.term+i} href={x.sourceUrl||"https://trends.google.com/trending?geo=BR&hl=pt-BR"} target="_blank" rel="noreferrer" className="rounded-lg border border-border p-4 hover:bg-[var(--surface2)]"><p className="font-medium">{x.term}</p><p className="text-xs text-[var(--muted)] mt-1">{x.traffic} · +{x.trendPercent}%</p></a>)}</div></section>
  <p className="text-xs text-[var(--muted)] mt-6">O radar não usa Google Ads. Quando não há dados do Search Console, o score de demanda é relativo e não deve ser interpretado como volume mensal.</p>
 </div>
}